name: GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true

jobs:
  verify_markdown:
    name: Verify Markdown files
    runs-on: ubuntu-18.04

    env:
      NuGet_Configuration_File: ./nuget.config
      Documentation_Root_Directory: ./presentation

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Install .NET local tools
      run: dotnet tool restore --configfile ${{ env.NuGet_Configuration_File }}
    - name: Verify interactive project
      run: dotnet try verify ${{ env.Documentation_Root_Directory }}
